from typing import Protocol
from apps.domain.entities.problem import Problem


class ProblemRepository(Protocol):
    def get_by_id(self, problem_id: int) -> Problem | None: ...
    def list(self) -> list[Problem]: ...
    def create(self, problem: Problem) -> Problem: ...
